spring:
  application:
    name: url-shortner-sb
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/urlshortnerdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 8080








